version: 2.3.4.{build}
init:
- dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
configuration: Release
before_build:
- cd src
- nuget restore
build:
  verbosity: minimal
  project: ./src/Solid.sln
test_script:
- cd ../devops/test
- test-all.bat
- cd ../../
after_test:
- cd devops
- cd pack
- pack-all
image: Visual Studio 2022
notifications:
- provider: Email
  to:
  - godrose@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
artifacts:
- name: Packages
  path: ./output/*.nupkg
- name: Bootstrapping Living Documentation
  path: ./output/Solid.Bootstrapping.Specs.LivingDoc.html
- name: Extensibility Living Documentation
  path: ./output/Solid.Extensibility.Specs.LivingDoc.html
- name: BoDi Adapter Living Documentation
  path: ./output/Solid.Ioc.Adapters.BoDi.Specs.LivingDoc.html
- name: Registration Living Documentation
  path: ./output/Solid.IoC.Registration.Specs.LivingDoc.html
- name: Composition Container Living Documentation
  path: ./output/Solid.Practices.Composition.Container.Specs.LivingDoc.html
- name: Composition Living Documentation
  path: ./output/Solid.Practices.Composition.Specs.LivingDoc.html
- name: Middleware Living Documentation
  path: ./output/Solid.Practices.Middleware.Specs.LivingDoc.html
...
