init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  project: Solid.sln

test_script:
  - cd
  - cd .\devops\test
  - test-all.bat
  - cd ..\..\

after_test:
  - mkdir packages
  - cd devops
  - cd pack
  - pack-all

image: Visual Studio 2019
  
notifications:
- provider: Email
  to:
  - godrose@gmail.com  
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
    
artifacts:
  
  - name: Bootstrapping Living Documentation
    path: .\Solid.Bootstrapping.Specs\bin\Release\LivingDoc.html

  - name: Extensibility Living Documentation
    path: .\Solid.Extensibility.Specs\bin\Release\LivingDoc.html

  - name: BoDi Adapter Living Documentation
    path: .\Solid.IoC.Adapters.BoDi.Specs\bin\Release\LivingDoc.html

  - name: Composition Container Living Documentation
    path: .\Solid.Practices.Composition.Container.Specs\bin\Release\LivingDoc.html

  - name: Composition Living Documentation
    path: .\Solid.Practices.Composition.Specs\bin\Release\LivingDoc.html

  - name: Middleware Living Documentation
    path: .\Solid.Practices.Middleware.Specs\bin\Release\LivingDoc.html
    
