configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  project: Solid.sln

image: Visual Studio 2019
  
notifications:
- provider: Email
  to:
  - godrose@gmail.com  
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
