configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  
install: 
  - cmd: choco install dotnetcore-sdk --pre

image: Visual Studio 2017
  
notifications:
- provider: Email
  to:
  - godrose@gmail.com  
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
