init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  project: Solid.sln

test_script:
  - cd .\devops\test\test-all.bat
  - cd ..\..\

image: Visual Studio 2019
  
notifications:
- provider: Email
  to:
  - godrose@gmail.com  
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
    
artifacts:

  # pushing a single file
  - path: .\Solid.Bootstrapping.Specs\bin\Release\LivingDoc.html
